// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFzQRfMSyAOEPkXRW0sXWWUwT5b9es86A',
    appId: '1:112454016306:web:5f5ab56b3d761cb4420b2b',
    messagingSenderId: '112454016306',
    projectId: 'irigation-monitor-app',
    authDomain: 'irigation-monitor-app.firebaseapp.com',
    databaseURL:
        'https://irigation-monitor-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'irigation-monitor-app.appspot.com',
    measurementId: 'G-JEH2WZJ1DD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlCgLL5Rv-B1LduFIIGsDpUbUz6QdUIe8',
    appId: '1:112454016306:android:1cd968c4458e54fa420b2b',
    messagingSenderId: '112454016306',
    projectId: 'irigation-monitor-app',
    databaseURL:
        'https://irigation-monitor-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'irigation-monitor-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvXgxc7Q7ue7_AHR8FopOf0DlrXubUcGI',
    appId: '1:112454016306:ios:8289913324ea1d76420b2b',
    messagingSenderId: '112454016306',
    projectId: 'irigation-monitor-app',
    databaseURL:
        'https://irigation-monitor-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'irigation-monitor-app.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvXgxc7Q7ue7_AHR8FopOf0DlrXubUcGI',
    appId: '1:112454016306:ios:b7440b3e253bc4b7420b2b',
    messagingSenderId: '112454016306',
    projectId: 'irigation-monitor-app',
    databaseURL:
        'https://irigation-monitor-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'irigation-monitor-app.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
